# Generated by Django 3.0.3 on 2020-06-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='username')),
                ('icon', models.ImageField(blank=True, default='icons/noname.jpg', null=True, upload_to='icons/', verbose_name='icon')),
                ('password1', models.CharField(max_length=30, verbose_name='password1')),
                ('password2', models.CharField(max_length=30, verbose_name='password2')),
            ],
        ),
    ]
