# Generated by Django 3.0.3 on 2020-06-18 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='icon',
        ),
    ]
